// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxmyt-cCBXEm-MkCf8B4Giep8Dw9hxVpE',
    appId: '1:934551169018:web:5018675dc30c6fcd00a643',
    messagingSenderId: '934551169018',
    projectId: 'ecommerce-e1adb',
    authDomain: 'ecommerce-e1adb.firebaseapp.com',
    storageBucket: 'ecommerce-e1adb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC68y-P3BY-tPUkmKxi-59koSXgUD6WnyA',
    appId: '1:934551169018:android:61d558da6494c65200a643',
    messagingSenderId: '934551169018',
    projectId: 'ecommerce-e1adb',
    storageBucket: 'ecommerce-e1adb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEo95cz2W5HjBPWRo0O3ktr5kee3fiNnA',
    appId: '1:934551169018:ios:8a895940a9501d9a00a643',
    messagingSenderId: '934551169018',
    projectId: 'ecommerce-e1adb',
    storageBucket: 'ecommerce-e1adb.appspot.com',
    iosBundleId: 'com.example.eCommerceStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEo95cz2W5HjBPWRo0O3ktr5kee3fiNnA',
    appId: '1:934551169018:ios:8a895940a9501d9a00a643',
    messagingSenderId: '934551169018',
    projectId: 'ecommerce-e1adb',
    storageBucket: 'ecommerce-e1adb.appspot.com',
    iosBundleId: 'com.example.eCommerceStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxmyt-cCBXEm-MkCf8B4Giep8Dw9hxVpE',
    appId: '1:934551169018:web:54816a2e4a49352800a643',
    messagingSenderId: '934551169018',
    projectId: 'ecommerce-e1adb',
    authDomain: 'ecommerce-e1adb.firebaseapp.com',
    storageBucket: 'ecommerce-e1adb.appspot.com',
  );
}